# Generated by Django 2.2.6 on 2019-11-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_auto_20191112_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='confirmar_pw',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
