# Generated by Django 2.2.6 on 2019-11-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0005_auto_20191112_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
