# Generated by Django 2.2.6 on 2019-11-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0006_auto_20191112_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas'),
        ),
    ]
