# Generated by Django 2.2.6 on 2019-11-15 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0007_auto_20191112_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='año_estreno',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
