# Generated by Django 2.2.6 on 2019-11-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0008_topic_año_estreno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='año_estreno',
            new_name='anho_estreno',
        ),
    ]
