# Generated by Django 2.2.6 on 2019-11-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0010_auto_20191116_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='descargar',
            field=models.TextField(blank=True, null=True, verbose_name='Link Descarga'),
        ),
    ]
