# Generated by Django 2.2.6 on 2019-11-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0011_auto_20191116_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='descargar',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Link Descarga'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='portada',
            field=models.ImageField(blank=True, default='question_mark.jpg', null=True, upload_to='portadas'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
